version: '3.8'

services:
  minikanban-db:
    image: postgres:16
    container_name: minikanban-db
    environment:
      POSTGRES_DB: MiniKanbanDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
